# Generated by Django 6.0.3 on 2026-03-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateField(verbose_name='Publishing Date')),
                ('edition', models.IntegerField(blank=True, null=True, verbose_name='Edition')),
                ('file_path', models.CharField(blank=True, help_text='Absolute path to the .cbz file on your computer/network.', max_length=1000, null=True, verbose_name='File Path')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'unique_together': {('publishing_date', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='IssueCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/', verbose_name='Image')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='core.issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Issue Cover',
                'verbose_name_plural': 'Issue Covers',
            },
        ),
        migrations.CreateModel(
            name='IssueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(blank=True, help_text='The physical page number where this section starts in the issue.', null=True, verbose_name='Page')),
                ('page_indexes', models.TextField(blank=True, default='', help_text='Comma-separated list of image indexes in the CBZ file.', verbose_name='Page Indexes')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue', verbose_name='Issue')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Issue Section',
                'verbose_name_plural': 'Issue Sections',
                'ordering': ['issue', 'page', 'section__name'],
                'unique_together': {('issue', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Role')),
                ('issue_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issuesection', verbose_name='IssueSection')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'ordering': ['issue_section__issue__publishing_date', 'role', 'person'],
            },
        ),
    ]
