# Generated by Django 6.0.3 on 2026-04-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateField()),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-publishing_date', '-edition'],
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='IssueCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/', verbose_name='Image')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='core.issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Issue Cover',
                'verbose_name_plural': 'Issue Covers',
            },
        ),
        migrations.CreateModel(
            name='IssueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, help_text='Optional textual content of the section.', null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_sections', to='core.issue', verbose_name='Issue')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.magazine'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Role')),
                ('issue_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.issuesection', verbose_name='IssueSection')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'ordering': ['issue_section__issue__publishing_date', 'issue_section__id', 'role', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='RenderAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.ImageField(upload_to='pages/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='core.issue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.issue')),
                ('render', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.renderasset')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SectionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('issue_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.issuesection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('publishing_date', 'edition'), name='unique_issue_per_date_edition'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('magazine', 'edition'), name='unique_issue_per_magazine_edition'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('issue', 'number')},
        ),
    ]
