# Generated by Django 6.0.3 on 2026-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='renderasset',
            constraint=models.UniqueConstraint(fields=('issue', 'order'), name='unique_render_order_per_issue'),
        ),
    ]
