# Generated by Django 6.0.3 on 2026-04-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='issuesection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='credit',
            name='issue_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.issuesection', verbose_name='IssueSection'),
        ),
        migrations.AlterField(
            model_name='issuesection',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.issue', verbose_name='Issue'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('publishing_date', 'edition'), name='unique_issue_per_date_edition'),
        ),
        migrations.AddConstraint(
            model_name='issuesection',
            constraint=models.UniqueConstraint(fields=('issue', 'section'), name='unique_section_per_issue'),
        ),
    ]
