# Generated by Django 6.0.3 on 2026-04-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_section_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueCover',
        ),
    ]
