# Generated by Django 6.0.3 on 2026-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_issue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['issue_section__issue__publishing_date', 'issue_section__page', 'role', 'person__name'], 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-publishing_date', '-edition'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='issuesection',
            name='page_indexes',
            field=models.JSONField(blank=True, default=list, help_text='Comma-separated list of image indexes in the CBZ file.', verbose_name='Page Indexes'),
        ),
    ]
