# Generated by Django 6.0.3 on 2026-04-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_issuecover'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesection',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
