# Generated by Django 6.0.3 on 2026-04-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_magazine_issue_magazine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.magazine'),
        ),
    ]
