# Generated by Django 6.0.4 on 2026-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_issuesection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
