# Generated by Django 6.0.4 on 2026-05-04 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_page_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.person')),
            ],
        ),
    ]
