# Generated by Django 6.0.3 on 2026-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_magazine_country_alter_magazine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edition'),
        ),
    ]
