# Generated by Django 6.0.3 on 2026-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_issue_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesection',
            name='text_content',
            field=models.TextField(blank=True, help_text='Optional textual content of the section.', null=True),
        ),
    ]
