# Generated by Django 6.0.4 on 2026-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_biography_person_birth_date_person_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_focus_x',
            field=models.IntegerField(default=50, verbose_name='Photo Focus X (%)'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_focus_y',
            field=models.IntegerField(default=50, verbose_name='Photo Focus Y (%)'),
        ),
    ]
