# Generated by Django 6.0.4 on 2026-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person_photo_focus_x_person_photo_focus_y'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['importance', 'issue_section__issue__publishing_date', 'issue_section__id', 'role', 'person__name'], 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.AddField(
            model_name='credit',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Major'), (2, 'Regular'), (3, 'Minor')], default=1, verbose_name='Importance'),
        ),
    ]
