# Generated by Django 6.0.4 on 2026-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_credit_options_credit_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Major'), (2, 'Regular'), (3, 'Minor')], default=2, verbose_name='Importance'),
        ),
    ]
