# Generated by Django 6.0.4 on 2026-05-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_credit_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='render',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='core.renderasset', verbose_name='Specific Page'),
        ),
    ]
