# Generated by Django 6.0.4 on 2026-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_credit_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='has_physical_copy',
            field=models.BooleanField(default=False, verbose_name='Has Physical Copy'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_digital_complete',
            field=models.BooleanField(default=False, verbose_name='Is Digital Complete'),
        ),
    ]
