# Generated by Django 6.0.4 on 2026-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_issue_has_physical_copy_issue_is_digital_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='aliases',
            field=models.JSONField(blank=True, default=list, verbose_name='Aliases'),
        ),
        migrations.AddField(
            model_name='person',
            name='disambiguation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Disambiguation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('name', 'disambiguation'), name='unique_person_name_disambiguation', nulls_distinct=False),
        ),
    ]
