# Generated by Django 6.0.4 on 2026-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_person_aliases_person_disambiguation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='render',
        ),
        migrations.AddField(
            model_name='credit',
            name='renders',
            field=models.ManyToManyField(blank=True, related_name='credits', to='core.renderasset', verbose_name='Specific Pages'),
        ),
    ]
