# Generated by Django 6.0.4 on 2026-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tag_magazine_tags_person_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='core.tag'),
        ),
    ]
