# Generated by Django 6.0.4 on 2026-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_issue_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Is Special Edition'),
        ),
    ]
