# Generated by Django 6.0.4 on 2026-05-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_issue_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino'), ('TM', 'Transsexual Masculino'), ('TF', 'Transsexual Feminino'), ('I', 'Intersexual'), ('NB', 'Não-binário')], max_length=2, null=True, verbose_name='Gênero'),
        ),
    ]
