# Generated by Django 6.0.4 on 2026-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Death Date'),
        ),
    ]
