# Generated by Django 6.0.4 on 2026-05-08 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_person_death_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RenderAsset',
            new_name='Render',
        ),
        migrations.AddField(
            model_name='render',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='render',
            name='page_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SPREAD', 'Página Dupla'), ('GATEFOLD', 'Desdobrável')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='render',
            name='focus_x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='render',
            name='focus_y',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='render',
            name='image',
            field=models.ImageField(upload_to='renders/'),
        ),
        migrations.AddField(
            model_name='render',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='render',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='render',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='core.issue'),
        ),
    ]
