# Generated by Django 6.0.4 on 2026-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_render_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='render',
            name='focus_x',
            field=models.IntegerField(default=0),
        ),
    ]
