# Generated by Django 6.0.4 on 2026-05-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_render_focus_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label (From -> To)')),
                ('inverse_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inverse Label (To -> From)')),
                ('order', models.IntegerField(default=0)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.person')),
            ],
            options={
                'verbose_name': 'Person Relationship',
                'verbose_name_plural': 'Person Relationships',
                'ordering': ['order', 'id'],
            },
        ),
    ]
