# Generated by Django 6.0.5 on 2026-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_personrelationship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='unique_page_number_per_issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='source_file',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
