# Generated by Django 6.0.5 on 2026-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_page_unique_page_number_per_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
