# Generated by Django 6.0.5 on 2026-05-24 11:45

from django.db import migrations, models

def seed_countries(apps, schema_editor):
    CountryMapping = apps.get_model('core', 'CountryMapping')
    countries = [
        ('brasil', 'br'),
        ('brazil', 'br'),
        ('eua', 'us'),
        ('usa', 'us'),
        ('united states', 'us'),
        ('frança', 'fr'),
        ('france', 'fr'),
        ('itália', 'it'),
        ('italy', 'it'),
        ('espanha', 'es'),
        ('spain', 'es'),
        ('alemanha', 'de'),
        ('germany', 'de'),
        ('reino unido', 'gb'),
        ('united kingdom', 'gb'),
        ('uk', 'gb'),
        ('japão', 'jp'),
        ('japan', 'jp'),
        ('portugal', 'pt'),
        ('argentina', 'ar'),
        ('canadá', 'ca'),
        ('canada', 'ca'),
        ('coreia do sul', 'kr'),
        ('south korea', 'kr'),
        ('korea', 'kr'),
        ('burkina faso', 'bf'),
        ('burkina fasso', 'bf'),
        ('bélgica', 'be'),
        ('belgium', 'be'),
        ('méxico', 'mx'),
        ('mexico', 'mx'),
        ('china', 'cn'),
    ]
    for name, code in countries:
        CountryMapping.objects.get_or_create(name=name, code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_magazine_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Common name or alias of the country (e.g. 'brasil', 'coreia do sul', 'kr')", max_length=255, unique=True)),
                ('code', models.CharField(help_text="2-letter ISO 3166-1 country code (e.g. 'br', 'kr', 'bf')", max_length=2)),
            ],
            options={
                'verbose_name': 'Country Mapping',
                'verbose_name_plural': 'Country Mappings',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_countries),
    ]
