# Generated by Django 6.0.5 on 2026-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_countrymapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issue',
            name='unique_issue_per_date_edition',
        ),
        migrations.RemoveConstraint(
            model_name='issue',
            name='unique_issue_per_magazine_edition',
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('magazine', 'volume', 'edition'), name='unique_issue_per_magazine_volume_edition', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('magazine', 'volume', 'publishing_date'), name='unique_issue_per_magazine_volume_date', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='magazine',
            constraint=models.UniqueConstraint(fields=('name', 'volume'), name='unique_magazine_name_volume', nulls_distinct=False),
        ),
    ]
