# Generated by Django 6.0.5 on 2026-06-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tag_description_tag_image_tag_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSectionRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label (From -> To)')),
                ('inverse_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inverse Label (To -> From)')),
                ('order', models.IntegerField(default=0)),
                ('from_issue_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.issuesection')),
                ('to_issue_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.issuesection')),
            ],
            options={
                'verbose_name': 'IssueSection Relationship',
                'verbose_name_plural': 'IssueSection Relationships',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('from_issue_section', 'to_issue_section'), name='unique_issuesection_relationship')],
            },
        ),
    ]
