# Generated by Django 6.0.5 on 2026-06-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_issuesectionrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Is Group'),
        ),
        migrations.AddField(
            model_name='person',
            name='members',
            field=models.JSONField(blank=True, default=list, verbose_name='Members'),
        ),
    ]
