# Generated by Django 6.0.5 on 2026-06-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_person_is_group_person_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ['volume', 'name']},
        ),
    ]
