# Generated by Django 6.0.5 on 2026-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_magazine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesection',
            name='translated_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
