# Generated by Django 6.0.5 on 2026-06-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_issuesection_translated_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('translated_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publishers/')),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='publisher',
        ),
        migrations.CreateModel(
            name='MagazinePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_publishers', to='core.magazine')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_publishers', to='core.publisher')),
            ],
            options={
                'ordering': ['start_date', 'publisher__name'],
            },
        ),
        migrations.AddField(
            model_name='magazine',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='magazines', through='core.MagazinePublisher', to='core.publisher'),
        ),
        migrations.AddConstraint(
            model_name='magazinepublisher',
            constraint=models.UniqueConstraint(fields=('magazine', 'publisher'), name='unique_magazine_publisher'),
        ),
    ]
