# Generated by Django 6.0.5 on 2026-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_publisher_remove_magazine_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
